<?php

namespace AudioCoreEntity\Repository;

use AudioCoreEntity\Entity\RadioHit;
use Doctrine\ORM\EntityRepository;

/**
 * RadioHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioHitRepository extends EntityRepository
{
    /**
     * @param $minSimilarity
     * @param $artist
     * @param $title
     * @return RadioHit[]
     */
    public function getSimilar($artist, $title, $minSimilarity = 51)
    {
        $query = $this->_em->createQuery('SELECT r FROM RadioHit r WHERE LEVENSHTEIN_RATIO(CONCAT(r.artist, \' \', title), :artistTitle) > :minSimilarity');
        $query->setParameter('artistTitle', sprintf('%s %s', $artist, $title));
        $query->setParameter('minSimilarity', $minSimilarity);

        return $query->getResult();
    }
}
